name: flutter_web3_games
description: Iranian eSport Community

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  socket_io_client: ^2.0.3+1
  get: ^4.6.6
  dio: ^5.4.1
  http_interceptor: ^1.0.2
  animations: ^2.0.11
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_gen_runner: ^5.4.0
  easy_localization: ^3.0.5
  bubble_tab_indicator: ^0.1.6
  flutter_easyloading: ^3.0.5
  bitsdojo_window: ^0.1.6
  confetti: ^0.7.0
  flutter_svg: ^2.0.10+1
  custom_pop_up_menu: ^1.2.4
  animated_background:
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  qlevar_router: ^1.10.2
  google_fonts: ^6.1.0

  #  window_size:
  #    git:
  #      url: https://github.com/google/flutter-desktop-embedding.git
  #      path: plugins/window_size


  url_launcher: ^6.2.5
  qr_flutter: ^4.1.0
  #  web3dart:
  #  dart_web3:
  #  flutter_web3:
#  walletconnect_dart: ^0.0.3
#  flutter_web3:

  # web3dart
  web3dart: ^2.7.2


  web3modal_flutter:
    git:
      url: https://github.com/hosseinkhojany/Web3ModalFlutter
      ref: master




  #flutter map
  flutter_map: ^6.1.0


#  flutter_ipfs: ^0.0.2
#  ipfs_client_flutter: ^1.0.7
#  https://github:com/hackyguru/IPFS-Flutter:



dependency_overrides:
  async: ^2.11.0
  http: ^1.1.2

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  mockito: ^5.4.4
#  pedantic: ^1.11.1
#  build_runner: ^2.4.8
#  build_test: ^2.2.2
#  test: ^1.25.2
#  coverage: ^1.7.2
#  flutter_lints: ^3.0.1



flutter_gen:
  output: lib/core/gen/ # Optional (default: fluttermap/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  fonts:
    - family: anjoman
      fonts:
        - asset: assets/fonts/anjoman_regular.ttf
        - asset: assets/fonts/anjoman_bold.ttf
    - family: ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_mono_regular.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/languages/
    - assets/fonts/
    - assets/google_fonts/

#    fonts:
#      - family: Raleway
#        fonts:
#          - asset: assets/fonts/Raleway-Regular.ttf
#          - asset: assets/fonts/Raleway-Italic.ttf
#            style: italic
